FROM openeuler/openeuler:24.03-lts-sp1 as openeuler
ARG TARGETARCH
ENV OS=openEuler
ENV OS_VERSION=24.03
ARG BUILD_TOOLS="findutils dnf-utils createrepo genisoimage"
ARG DIR=${OS}${OS_VERSION}-${TARGETARCH}-rpms
COPY container-selinux.repo k3s-common.repo /etc/yum.repos.d/
RUN yum install -q -y ${BUILD_TOOLS} \
    && yum makecache
WORKDIR package
COPY packages.yaml .
COPY --from=mikefarah/yq:4.11.1 /usr/bin/yq /usr/bin/yq
RUN yq eval ".common[],.${OS}[],.${OS}${OS_VERSION}[]" packages.yaml > packages.list
RUN sort -u packages.list | xargs repotrack --destdir ${DIR} \
    && createrepo -d ${DIR} \
    && genisoimage -r -o ${DIR}.iso ${DIR}

FROM scratch
COPY --from=openeuler /package/*.iso /
