FROM centos:7 as centos7
ARG TARGETARCH
ENV OS=centos
ENV OS_VERSION=7
ARG BUILD_TOOLS="yum-utils createrepo mkisofs epel-release"
ARG DIR=${OS}${OS_VERSION}-${TARGETARCH}-rpms
RUN rm -f /etc/yum.repos.d/*
COPY k3s-common.repo Centos7-tencent-x86_64.repo Centos7-tencent-altarch.repo /etc/yum.repos.d/
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    rm -f /etc/yum.repos.d/Centos7-tencent-altarch.repo; \
    else \
    rm -f /etc/yum.repos.d/Centos7-tencent-x86_64.repo; \
    fi
RUN yum makecache && yum install -q -y ${BUILD_TOOLS}
WORKDIR package
COPY packages.yaml .
COPY --from=mikefarah/yq:4.11.1 /usr/bin/yq /usr/bin/yq
RUN yq eval ".common[],.rpms[],.${OS}[],.${OS}${OS_VERSION}[]" packages.yaml > packages.list
RUN sort -u packages.list | xargs repotrack -p ${DIR} \
    && createrepo -d ${DIR} \
    && mkisofs -r -o ${DIR}.iso ${DIR}

FROM scratch
COPY --from=centos7 /package/*.iso /
